#include "Menu.h"


struct menu_item Menu[SIZE_OF_STRUCT]=
{											         	           //Parent      child      Previous      next
  /*0*/ 	{"Settings        ",0,             MENU,       	        NULL,       &Menu[1],   &Menu[39],    &Menu[21]  },
  /*1*/ 	{"Charge time, h  ",0,             MENU,      	        NULL,       &Menu[2],   &Menu[20],     &Menu[3]   },
  /*2*/ 	{"                ",0,             CHARGE_TIME,	        NULL,       &Menu[1],   NULL,         NULL       },
  /*3*/ 	{"Low Volt, mV*10 ",0,             MENU,       	        NULL,       &Menu[4],   &Menu[1],    &Menu[5]   },
  /*4*/ 	{"                ",0,             LOW_VOLTAGE,	        NULL,       &Menu[3],  NULL,         NULL       },
  /*5*/ 	{"Max Volt, mV*10 ",0,             MENU,       	        NULL,       &Menu[6],   &Menu[3],    &Menu[7]   },
  /*6*/ 	{"                ",0,             MAX_VOLTAGE,         NULL,       &Menu[5],  NULL,         NULL       },
  /*7*/ 	{"Swng Chrg Time,s",0,             MENU,     	        NULL,       &Menu[8],   &Menu[5],    &Menu[9]   },
  /*8*/ 	{"                ",0,             SWING_CHRG_TIME,     NULL,       &Menu[7],  NULL,         NULL       },
  /*9*/ 	{"SwngDChrg Time,s",0,             MENU,     	        NULL,       &Menu[10],  &Menu[7],    &Menu[11]   },
  /*10*/	{"                ",0,             SWING_DCHRG_TIME,    NULL,       &Menu[9],  NULL,         NULL       },
  /*11*/ 	{"Charge addapt, %",0,             MENU,     	        NULL,       &Menu[12],  &Menu[9],    &Menu[20]   },
  /*12*/	{"                ",0,             CHARGE_ADAPT,        NULL,       &Menu[11],  NULL,         NULL       },
  /*13*/ 	{"xxxxxxxxxxxxxx,s",0,             MENU,     	        NULL,       &Menu[14],  &Menu[11],    &Menu[15]   },
  /*14*/	{"                ",0,             SWING_DCHRG_TIME,    NULL,       &Menu[13],  NULL,         NULL       },
  /*15*/ 	{"xxxxxxxxxxxxxx,s",0,             MENU,     	        NULL,       &Menu[16],  &Menu[13],    &Menu[20]   },
  /*16*/	{"                ",0,             SWING_DCHRG_TIME,    NULL,       &Menu[15],  NULL,         NULL       },
  /*17*/	{"SubMenu         ",0,             MENU,                NULL,       &Menu[2],   NULL,        NULL       },
  /*18*/	{"Option 1        ",UNSET,         OPTION,    	  	    NULL,       &Menu[13],  &Menu[2],    &Menu[14]  },
  /*19*/	{"Option 1        ",SET,           OPTION,              NULL,       &Menu[12],  NULL, 		 NULL       },
  /*20*/	{"OK to Exit      ",0,             MENU,       	        NULL,       &Menu[0],  &Menu[11],   &Menu[1]  },
  /*21*/	{"PowerSupply     ",0,             MENU,                NULL,       &Menu[22],  &Menu[0],  &Menu[23]       },
  /*22*/	{"                ",0,             POWERSUPPLY,       	NULL,       &Menu[21],   NULL,         NULL       },
  /*23*/	{"Load            ",0,             MENU,                NULL,       &Menu[24],  &Menu[21],  &Menu[25]       },
  /*24*/	{"                ",0,             LOAD,     		  	NULL,       &Menu[23],   NULL,         NULL       },
  /*25*/	{"Charge CC CV    ",0,             MENU,          		NULL,       &Menu[26],  &Menu[23],   &Menu[27]  },
  /*26*/	{"                ",0,             CHARGE,       	    NULL,       &Menu[25],  NULL,         NULL       },
  /*27*/	{"Charge addapt   ",0,             MENU,          		NULL,       &Menu[28],  &Menu[25],   &Menu[31]  },
  /*28*/	{"                ",0,             CHARGE_ADAPT_MENU,   NULL,       &Menu[27],  NULL,         NULL       },
  /*29*/	{"11Charge        ",0,             MENU,          		NULL,       &Menu[30],  &Menu[27],   &Menu[31]  },
  /*30*/	{"                ",0,             CHARGE,       	    NULL,       &Menu[29],  NULL,         NULL       },
  /*31*/	{"DisCharge       ",0,             MENU,       	        NULL,       &Menu[32],  &Menu[27],   &Menu[33]   },
  /*32*/	{"                ",0,             DISCHARGE,       	NULL,       &Menu[31],  NULL,         NULL       },
  /*33*/	{"Training        ",0,             MENU,       	        NULL,       &Menu[34],  &Menu[31],   &Menu[35]   },
  /*34*/	{"                ",0,             TRAINING,       	    NULL,       &Menu[33],   NULL,         NULL       },
  /*35*/	{"Swing           ",0,             MENU,       	        NULL,       &Menu[36],  &Menu[33],   &Menu[37]   },
  /*36*/	{"                ",0,             SWING,       	    NULL,       &Menu[35],  NULL,         NULL       },
  /*37*/	{"DIAGNOSTIC      ",0,             MENU,       	        NULL,       &Menu[38],  &Menu[35],   &Menu[39]   },
  /*38*/	{"                ",0,             DIAGNOSTIC,       	NULL,       &Menu[37],   NULL,         NULL       },
  /*39*/	{"CALIBRATION     ",0,             MENU,      		   	NULL,       &Menu[40],   &Menu[37],   &Menu[0]       },
  /*40*/	{"CURRENT Out to 0",0,             MENU,       			NULL,       &Menu[41],   &Menu[58] ,  &Menu[42]       },
  /*41*/	{"                ",0,             CURRENTSET0,        	NULL,       &Menu[40],   NULL,         NULL       },
  /*42*/	{"CURRENT Load to0",0,             MENU,       			NULL,       &Menu[43],   &Menu[40] ,   &Menu[44]       },
  /*43*/	{"                ",0,             CURRENT1SET0,        NULL,       &Menu[42],   NULL,         NULL       },
  /*44*/	{"CURRENT Out     ",0,             MENU,       			NULL,       &Menu[45],   &Menu[42] ,   &Menu[46]        },
  /*45*/	{"                ",0,             CURRENTOUT,     	 	NULL,       &Menu[44],   NULL,         NULL       },
  /*46*/	{"CURRENT Load    ",0,             MENU,       			NULL,       &Menu[47],   &Menu[44] ,   &Menu[48]        },
  /*47*/	{"                ",0,             CURRENTLOAD,    	 	NULL,       &Menu[46],   NULL,         NULL       },
  /*48*/	{"Voltage PS      ",0,             MENU,       			NULL,       &Menu[49],   &Menu[46] ,   &Menu[50]        },
  /*49*/	{"                ",0,             VOLTAGE,     	  	NULL,       &Menu[48],   NULL,         NULL       },
  /*50*/	{"Voltage Out     ",0,             MENU,       			NULL,       &Menu[51],   &Menu[48] ,   &Menu[52]        },
  /*51*/	{"                ",0,             VOLTAGE1,    	   	NULL,       &Menu[50],   NULL,         NULL       },
  /*52*/	{"Voltage In      ",0,             MENU,       			NULL,       &Menu[53],   &Menu[50] ,   &Menu[54]        },
  /*53*/	{"                ",0,             VOLTAGEIN,     	  	NULL,       &Menu[52],   NULL,         NULL       },
  /*54*/	{"Resist comp 5V1A",0,             MENU,       			NULL,       &Menu[55],   &Menu[52] ,   &Menu[56]        },
  /*55*/	{"                ",0,             RESISTANCE_COMP,	  	NULL,       &Menu[54],   NULL,         NULL       },
  /*56*/	{"Back to Factory ",0,             MENU,       			NULL,       &Menu[57],   &Menu[54] ,   &Menu[58]        },
  /*57*/	{"                ",0,             BACKTOFACTORY,    	NULL,       &Menu[56],   NULL,         NULL       },
  /*58*/	{" OK to Exit     ",0,             MENU,        		NULL,       &Menu[39],   &Menu[56] ,    &Menu[40]        },
};




